### ISSUE TITLE
How can I pass options to a homebrew formula (`brew install emacs-plus [options]`)?

### ISSUE THREAD

**Issue by oscarvarto** [zhaofengli/nix-homebrew#11]
Hi!

I would like to install the equivalent of:
```
brew install emacs-plus --with-xwidgets --with-native-comp --with-poll
```

from https://github.com/d12frosted/homebrew-emacs-plus.

How could pass the flags `--with-xwidgets --with-native-comp --with-poll` to the formula?

**Comment by zhaofengli** [comment]
Hi, this module only sets up Homebrew itself and the taps, and doesn't perform installation of any formula. You can use [the base `homebrew` module](https://daiderd.com/nix-darwin/manual/index.html#opt-homebrew.brews) in nix-darwin to install packages.

**Comment by oscarvarto** [comment]
@zhaofengli Thank you very much for the guidance.
