### ISSUE TITLE
homebrew prefix not in path

### ISSUE THREAD

**Issue by genebean** [zhaofengli/nix-homebrew#14]
On Apple Silicon, it seems that the brew prefix is not part of my path nor are any of the homebrew environment variable exported. Should these be being added automatically or am I supposed to be calling `eval $(brew shellenv)` or similar in my zsh config? For what its worth, I use home manager to configure zsh.

**Comment by Swoorup** [comment]
Have the same issue in fish.

**Comment by zhaofengli** [comment]
Right, this module does not apply any shell configurations at the moment, but it would be useful to add.
