### ISSUE TITLE
Issue with newest version of `homebrew-core`

### ISSUE THREAD

**Issue by Dekker1** [zhaofengli/nix-homebrew#22]
I ran into an issue where the newer version of the `homebrew-core` tap, caused an issue since it used a new function, not present in the current version installed by nix-homebrew.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/x/xz.rb#L26

The error I receive is:
```
Error: homebrew/core/xz: undefined method `deny_network_access!' for Formulary::FormulaNamespaced6af8689f9d67fe78906ee1d8991056d52b8b4735aad55203c61e4b64950bbbd::Xz:Class
```

I assume this issue is quickly resolved once the `brew` command version is updated, but it might be worth thinking about a way of locking taps to the version that is known to be supported.

**Comment by someones-github-account** [comment]
I'm experiencing this too, and can't find a way to fix it. Have you?

I've tried manually using `brew update`, but get: `/nix/store/na5j7bphjjfqn39hvn439x8qg83jpqbr-source/.git: Permission denied`

I've tried disabling homebrew and nix-homebrew in my nix-darwin flake, deleting `/opt/homebrew` and then re-enabling homebrew and nix-homebrew.

Sadly, I still get the same error as you @Dekker that prevents multiple formulae from installing,
eg

`Installing libxml2
==> Downloading https://ghcr.io/v2/homebrew/core/libxml2/manifests/2.12.6
Error: homebrew/core/xz: undefined method `deny_network_access!' for Formulary::FormulaNamespaced6af8689f9d67fe78906ee1d8991056d52b8b4735aad55203c61e4b64950bbbd::Xz:Class`

This includes if I try to re-install `xz` by adding it as a brew formula in `brews`.

I have also tried to disabling homebrew and nix-homebrew in my nix-darwin flake and re-installing homebrew without nix, which hasn't fixed this.

Any help is appreciated as sadly, I need to use some homebrew forumlae that aren't yet in nixpkgs.

Thanks

PS Is `homebrew-bundle` deprecated from nix-homebrew, as I don't see it in the readme, but it's in my flake?

**Comment by Dekker1** [comment]
I actually managed to work around the problem by adding
```nix
    brew-src = {
      url = "github:Homebrew/brew/4.3.0";
      flake = false;
    };
```

to my flake inputs. By then adding a `inputs.XXX.follows` to the `nix-homebrew` input:

```nix
    nix-homebrew = {
      url = "github:zhaofengli/nix-homebrew";
      inputs.brew-src.follows = "brew-src";
    };
```

I was able to upgrade the version of homebrew that was being used.

**Comment by someones-github-account** [comment]
Many thanks @Dekker1, that worked!

I thought I'd try what you no doubt did first, using `master` instead of `4.3.0` to avoid having to remember to change versions again in future if forgeting to change the url back, but was hit with a ruby version issue with a psych gem issue, so reverted to your approach. Mentioned should someone else see this and try to skip your workaround for `master`.
