### ISSUE TITLE
First Time installing homebrew

### ISSUE THREAD

**Issue by eyadsibai** [zhaofengli/nix-homebrew#32]
I am trying to use nix-homebrew on a fresh machine.

getting the following error:

`fatal: could not create work tree dir '/opt/homebrew/Library/Taps/homebrew/homebrew-bundle': Permission denied
`

**Comment by eyadsibai** [comment]
do I have to run 'sudo darwin-rebuild' ?

**Comment by Smona** [comment]
Looks like this might be a duplicate of #9? Does [this fix](https://github.com/zhaofengli/nix-homebrew/issues/9#issuecomment-1774684583) work for you?

**Comment by dezren39** [comment]
yeah that fixes it.
