### ISSUE TITLE
Feature Request: Add global greedy option in caskArgs

### ISSUE THREAD

**Issue by x6ufeng** [zhaofengli/nix-homebrew#52]
Currently, to enable greedy updates for casks, we need to manually add the greedy option to each cask definition like this:

casks = [
  {
    name = "anytype";
    greedy = true;
  }
  {
    name = "vscodium";
    greedy = true;
  }
];

This becomes tedious and repetitive when managing multiple casks. It would be more convenient to have a global option in caskArgs, similar to how no_quarantine works:

homebrew = {
  enable = true;
  caskArgs = {
    greedy = true;  # Would apply to all casks
    no_quarantine = true;
  };
  casks = [
    "anytype"
    "vscodium"
  ];
};

This would simplify configuration and maintain consistency across all casks while reducing the likelihood of configuration errors.

**Comment by zhaofengli** [comment]
Hi, this is better submitted to https://github.com/LnL7/nix-darwin.

This repo implements the `nix-homebrew.*` options which install Homebrew itself, and the `homebrew.*` options in upstream nix-darwin manage packages to be installed with Homebrew.

**Comment by x6ufeng** [comment]
> Hi, this is better submitted to https://github.com/LnL7/nix-darwin.
> 
> This repo implements the `nix-homebrew.*` options which install Homebrew itself, and the `homebrew.*` options in upstream nix-darwin manage packages to be installed with Homebrew.
> 
> Please leave a link here after you create the issue in the nix-darwin repo, thanks!

Thank you for your guidance. I've created the issue as suggested in the nix-darwin repository: https://github.com/LnL7/nix-darwin/issues/1201
