### ISSUE TITLE
brew bundle thinks no casks are installed

### ISSUE THREAD

**Issue by zmre** [zhaofengli/nix-homebrew#6]
I finally had a chance to add nix-homebrew to my setup and try it out. It's working as advertised (and thank you!), but with some kinks.

The first one is that on updating my system, every cask produces output like this:

```
Installing raycast
Installing raycast cask. It is not currently installed.
Warning: Cask 'raycast' is already installed.

To re-install raycast, run:
  brew reinstall --cask raycast
Installing screenflow
Installing screenflow cask. It is not currently installed.
Warning: Cask 'screenflow' is already installed.

To re-install screenflow, run:
  brew reinstall --cask screenflow
Installing signal
Installing signal cask. It is not currently installed.
Warning: Cask 'signal' is already installed.

To re-install signal, run:
  brew reinstall --cask signal
```

In trying to track down what's going on, I did a few things. The most enlightening was in running `brew bundle dump`, which resulted in a file that showed regular brews, taps, and vscode plugins, but no casks. So it sees a cask, which isn't in the internal list, attempts to install it, gets an error, then moves on. This is slow and I don't think it's upgrading things.

It seems the homebrew bundle stuff uses the same mechanism as `brew list` which shows all the installed casks successfully. But something must be different. I'm guessing it comes down to this file: 

https://github.com/Homebrew/homebrew-bundle/blob/master/lib/bundle/cask_dumper.rb

which relies on this module:

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/caskroom.rb

and also checks against this:

https://github.com/Homebrew/homebrew-bundle/blob/f3389cc6ab60a49ae01dfdd343beb937b1f48c55/lib/bundle/bundle.rb#L44

And it looks like it bails when `HOMEBREW_NO_INSTALL_FROM_API` is set.  In other words, with that set, the bundle stuff thinks no casks are installed and tries and fails to install everything from scratch.

It looks like that env var is needed to make sure the local (pinned) formulas are used though. Which leaves a quandary.

Are you able to reproduce? Any ideas on how to fix it?  Perhaps patch the `cask_installed` function in core homebrew?

**Comment by zmre** [comment]
This greatly slows down my flow when I'm not upgrading, but simply making config changes. It spends a bunch of time going through casks so the cycle of implementing small config tweaks is just a bit ugly. I love that the brew stuff is pinned and would love to help find a way to remove this tax.

**Comment by cloudyparts** [comment]
I have the same issue.  I recently found @dustinlyons had a similar [issue](https://github.com/dustinlyons/nixos-config/issues/16) and fixed it with setting additional permissions for `/opt/homebrew/Library/Taps/homebrew`

I replicated the permissions and it did not resolve this issue.

Hoping this information helps track down the issue.

**Comment by dustinlyons** [comment]
Hi, yes I saw this issue after installing `nix-homebrew` for the first time. As a side effect of fixing permissions on the homebrew taps dir (I don't run darwin-rebuild as `sudo`, so it was failing to write to the dir listed above), I noticed the install behavior changed.

<img width="320" alt="Screenshot 2023-09-20 at 10 45 52 AM" src="https://github.com/zhaofengli/nix-homebrew/assets/1292576/5bd38ba5-8de1-4f02-9f5e-30223e3accca">


```
sudo /bin/chmod +a "dustin allow list,add_file,search,delete,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,readsecurity,writesecurity,chown" /opt/homebrew/Library/Taps/homebrew/
```

```
FLAKE="Dustins-MBP"
SYSTEM="darwinConfigurations.$FLAKE.system"
nix --experimental-features 'nix-command flakes' build .#$SYSTEM
./result/sw/bin/darwin-rebuild switch --flake .#$FLAKE
```

**Comment by dustinlyons** [comment]
> I have the same issue. I recently found @dustinlyons had a similar [issue](https://github.com/dustinlyons/nixos-config/issues/16) and fixed it with setting additional permissions for `/opt/homebrew/Library/Taps/homebrew`
> 
> I replicated the permissions and it did not resolve this issue.
> 
> Hoping this information helps track down the issue.

I realized I created a bug when trying to make the script more abstract; $USER is actually `root` when running with sudo. So you need to drop $USER and replace with your actual username.

**Comment by zhaofengli** [comment]
This is indeed pretty annoying. I think [the path](https://github.com/Homebrew/homebrew-bundle/blob/f3389cc6ab60a49ae01dfdd343beb937b1f48c55/lib/bundle/bundle.rb#L46) they are using to check whether homebrew-cask is tapped should use `$HOMEBREW_LIBRARY` instead of `$HOMEBREW_REPOSITORY/Library`. The former is semantically more correct and also what's used in [Homebrew's self-update mechanism](https://github.com/Homebrew/brew/blob/1f80e82dd72fce6642e4ea360f7a1feef5d78470/Library/Homebrew/cmd/update.sh#L581) (`$HOMEBREW_REPOSITORY` for updating brew itself, `$HOMEBREW_LIBRARY/Taps/*/*` for all the taps). WIth that change I think our setup will work.

I'll confirm this in a bit with a vanilla install of Homebrew in a VM.

**Comment by zhaofengli** [comment]
With https://github.com/Homebrew/homebrew-bundle/pull/1250 applied, `brew bundle dump` lists all the installed casks for me.

For more context, since we pin Homebrew itself it's not possible for it to self-update. As a result, we set `HOMEBREW_REPOSITORY` to a different directory (`/opt/homebrew/Library/.homebrew-is-managed-by-nix`). The semantics of `HOMEBREW_LIBRARY` are unchanged and should be used to access all code and taps.

**Comment by zmre** [comment]
Sweet!  Thanks for tracking this down and making the PR. Can't wait for them to apply it.

**Comment by zmre** [comment]
Just tried it out and yes, it's working great now. Much faster and much better. Thank you!  I'll close this issue.

**Comment by cloudyparts** [comment]
Verified fixed on my M2 MBP.  Thank you @zhaofengli and @zmre!

**Comment by dustinlyons** [comment]
Yes this works great, thank you!
