### ISSUE TITLE
Unable to tap homebrew/bundle

### ISSUE THREAD

**Issue by flexwie** [zhaofengli/nix-homebrew#9]
When trying to switch to a flake with nix-homebrew enabled, I get the following error message:

```sh
==> Tapping homebrew/bundle
fatal: could not create work tree dir '/opt/homebrew/Library/Taps/homebrew/homebrew-bundle': Permission denied
Error: Failure while executing;  exited with 128.
```

I'm doing this on a fresh install if MacOS. Do I need to modify some permissions in order to get nix-homebrew to work?

**Comment by theowenyoung** [comment]
same...

**Comment by zhaofengli** [comment]
If you have `mutableTaps = false`, then you need to add the `homebrew/bundle` tap to your config to use nix-darwin's homebrew options.

**Comment by mg** [comment]
> If you have `mutableTaps = false`, then you need to add the `homebrew/bundle` tap to your config to use nix-darwin's homebrew options.

Hi @zhaofengli  sorry if I am asking for something obvious, but what does that mean? Do I add it do the nix-homebrew config or the darwin homebrew config? And what does it look like?

Sorry again, totally new to this and trying to figure out 100 things at the same time.

**Comment by zhaofengli** [comment]
There are two options to pull in taps:

1. Let homebrew manage them imperatively: When you run `brew tap koekeishiya/formulae`, Brew will automatically clone https://github.com/koekeishiya/homebrew-formulae into `$HOMEBREW_LIBRARY/Taps`. This is only possible if you have `mutableTaps = true`.
2. Declaratively specify them in your Nix configuration: All tap contents are stored in the Nix store and generated by your confioguration. When activating the nix-darwin configuration, the activation script will replace `$HOMEBREW_LIBRARY/Taps` with a link to the synthesized taps directory in the store. This is in effect when `mutableTaps = false`.

The problem you have now is that Brew will automatically run `brew tap homebrew/bundle` if you run `brew bundle` and the [bundle tap](https://github.com/Homebrew/homebrew-bundle) isn't tapped yet. This isn't possible with `mutableTaps = false`, and you will need to specify the `homebrew-bundle` repo in the config. With a `flake.nix`:

```nix
{
  inputs = {
    homebrew-bundle = {
      url = "github:homebrew/homebrew-bundle";
      flake = false;
    };
  };
}
```

Then, you may add it to your configuration:

```nix
{
  nix-homebrew = {
    enable = true;
    mutableTaps = false;
    // ....
    taps = {
      "homebrew/homebrew-core" = inputs.homebrew-core;
      "homebrew/homebrew-cask" = inputs.homebrew-cask;
      "homebrew/homebrew-bundle" = inputs.homebrew-bundle; // <---
    };
  };
}
```

**Comment by mg** [comment]
@zhaofengli thank you for taking time to write this very clear and very helpful explanation. And thank you for this package, it is great to be able to install brew as a part of a nix configuration.

**Comment by akavel** [comment]
Thank you so much @zhaofengli for this clarification!! Do you think it could make sense to add it to the readme? I feel like it might be useful to newbies like me ❤️
